# Generated by Django 5.1 on 2024-08-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='media')),
                ('nombre', models.CharField(max_length=40)),
                ('precio_proveedor', models.IntegerField(default=0)),
                ('precio_unidad', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_venta', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
    ]
