# Generated by Django 5.1 on 2024-09-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_stock_producto_modelo_stock_delete_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
