# Generated by Django 5.1 on 2024-09-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_modelo',
            name='descripcion',
        ),
    ]
