# Generated by Django 5.1 on 2024-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_producto_modelo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_modelo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='producto_modelo',
            name='nombre_variante',
            field=models.CharField(default='default nombre_variante', max_length=100),
            preserve_default=False,
        ),
    ]
