# Generated by Django 5.1 on 2024-09-07 20:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_producto_modelo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_modelo',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
