# Generated by Django 5.1 on 2024-09-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_modelo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_modelo',
            name='image',
            field=models.ImageField(null=True, upload_to='subprod'),
        ),
    ]
