# Generated by Django 5.1 on 2024-09-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_producto_modelo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_modelo',
            name='descripcion',
            field=models.TextField(default='default sub-description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventas',
            name='productos',
            field=models.ManyToManyField(to='app.producto_modelo'),
        ),
    ]
