# Generated by Django 5.1 on 2024-09-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_producto_modelo_descripcion_ventas_cerrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_modelo',
            name='color',
        ),
    ]
