# Generated by Django 5.1 on 2024-09-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_producto_modelo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_modelo',
            name='color',
            field=models.CharField(blank=True, default='#FF0000', max_length=7),
        ),
    ]
