# Generated by Django 5.1 on 2024-09-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_producto_modelo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_modelo',
            name='color',
        ),
    ]
